language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install numpy"
  - "pip install scipy"
  - "pip install matplotlib"

# command to run tests
script: python runtests.py